name: Docker Build and Push

on:
  push:
    branches:
      - main  # Ajusta si usas otra rama

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configurar Buildx
        uses: docker/setup-buildx-action@v2

      - name: Loguearse en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y empujar imagen
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mi-app-react:latest
